# extensions/asystent-klienta/shopify.extension.toml
name = "asystent-klienta"
handle = "asystent-klienta"

[[extensions]]
name = "AI Assistant"

# Używamy uida wygenerowanego przez Shopify CLI
uid = "f86b30a7-e5a7-5d4e-b33a-0a240196266ec1976fb8"
type = "theme"
handle = "ai-assistant"

# NOWE: Wersja Extension (dla lepszego śledzenia)
version = "1.1.2"
build = 12 

[extension]
target = "section"

# ===================================================================
# KONFIGURACJA APP PROXY
# ===================================================================

[extension.app_proxy]
# Wymagany ścieżka: /apps/assistant/chat (ostatni człon jest zdefiniowany w Workerze)
path = "/apps/assistant" 

# Wymagane: Definicja URL Workera/Tunelu dla różnych środowisk.
# Odczyt z globalnych zmiennych środowiskowych APP_URL z shopify.app.toml / Shopify CLI.

# W środowisku 'development' (shopify app dev) używa tunelu ngrok
# W środowisku 'production' (shopify app deploy) używa URL Workera
proxy_url = "$APP_URL" 

# NOWE: Używamy zmiennej środowiskowej do dynamicznego ustawienia dozwolonych domen.
# Zapewnia to, że tylko aktualny sklep dev lub produkcyjny sklep ma dostęp.
allowed_origins = [
  "$APP_URL",
  "$ALLOWED_SHOP_DOMAIN" 
]

[development]
# Opcje deweloperskie
