# Shopify app configuration for EPIR AI Assistant
client_id = "abbb8988e6c96ba5ca0c3545de0d3491"
name = "Agent EPIR Art Jewellery"
application_url = "https://epir-art-jewellery-worker.krzysztofdzugaj.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
prefix = "apps"
subpath = "assistant"
url = "https://epir-art-jewellery-worker.krzysztofdzugaj.workers.dev"

[extensions]
handle = "asystent-klienta"
